# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20171109_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='user_id',
        ),
    ]
