# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171129_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
