# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_pitchforkpayments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PitchforkPayments',
            new_name='Payments',
        ),
    ]
