# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('webapp', '0015_auto_20171205_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.TextField()),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
